In [17]:
# Create a 3D numpy array with values 1 to 27
import numpy as np

array_3d = np.arange(8).reshape((2, 2, 2))
print("3D Array:")
print(array_3d)

print('-------------trace of a 3D matrix---------------')

# Find the trace of the 3D array
# The trace is the sum of the diagonal elements in each 2D slice
print(np.trace(array_3d, axis1=0, axis2=1))
print(np.diagonal(array_3d, axis1=0, axis2=1))

3D Array:
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
-------------trace of a 3D matrix---------------
[6 8]
[[0 6]
 [1 7]]


In [9]:
import numpy as np

array_3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
# shape: (2, 2, 2)

result = np.trace(array_3)
# Calculation:
# For slice 0: [1, 4] → sum = 1 + 4 = 5
# For slice 1: [5, 8] → sum = 5 + 8 = 13
# Total: 5 + 13 = 18

print(result)
print(array_3.trace())

[ 8 10]
[ 8 10]
