In [5]:
import numpy as np

array_1 = np.arange(1, 10).reshape(3, 3)
print(array_1)
print(np.diagonal(array_1))
print(np.trace(array_1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]
15


In [10]:
array_2 = np.arange(1, 9).reshape(2, 2, 2)
print(array_2)
print(np.diagonal(array_2, axis1=0, axis2=1))
print(np.trace(array_2, axis1=0, axis2=1))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[1 7]
 [2 8]]
[ 8 10]


In [8]:
# Trace of a non-square matrix
array_3 = np.arange(1, 9).reshape(2, 4)
print(array_3)
print(np.trace(array_3))

[[1 2 3 4]
 [5 6 7 8]]
7


In [11]:
# Cross product of two vectors
# Formula: a x b = |a| |b| sin(θ) n
# where |a| and |b| are the magnitudes of vectors a and b,
# θ is the angle between them, and n is the unit vector perpendicular to both a and b.

vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])
# Calculate the cross product
cross_product = np.cross(vector_a, vector_b)
print("Cross product of vectors a and b:", cross_product)


Cross product of vectors a and b: [-3  6 -3]
